version: "3"
services:
  db:
    build:
      context: ./infra/db
      dockerfile: Dockerfile
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: app_test
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "3306:3306"
    volumes:
      - rails-railway-stations-volume:/var/lib/mysql

  web:
    build:
      context: .
      dockerfile: ./infra/web/Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && service cron start && bundle install && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      TZ: Asia/Tokyo
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    links:
      - db
      - redis
  redis:
    container_name: redis
    image: "redis:7.2.4"
    ports:
      - "6379:6379"
    volumes:
      - "./data/redis:/data"
      - "./app/infra/redis/conf/redis.conf:/etc/redis.conf"

volumes:
  rails-railway-stations-volume:
  bundle:
